version: '3.8'

services:

    php:
        build:
            context: php
            args:
                - COMPOSER_VERSION=${COMPOSER_VERSION}
                - GID=${USER_GID}
                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
                - PHP_VERSION=${PHP_VERSION}
                - UID=${USER_UID}
        volumes:
            - ./project:/usr/share/nginx/html
        working_dir: /usr/share/nginx/html
        restart: unless-stopped
        command: bash -c "service php${PHP_VERSION}-fpm start && tail -F anything"
        environment:
            DOCKERHOST: $DOCKERHOST

    nginx:
        build: 
            context: nginx
            args:
                - NGINX_VERSION=${NGINX_VERSION}
        restart: unless-stopped
        ports:
            - ${NGINX_PORT}:80
        working_dir: /etc/nginx/conf.d
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d

    mysql:
        build:
            context: mysql
            args:
                - MYSQL_VERSION=${MYSQL_VERSION}
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes: 
            - ./mysql_databases:/var/lib/mysql
            - ./project:/usr/share/nginx/html
        ports:
            - ${MYSQL_PORT}:3306
        working_dir: /usr/share/nginx/html

    adminer:
        image: adminer
        ports:
            - ${ADMINER_PORT}:8080

    mongo:
        build:
            context: mongo
            args:
                - MONGO_VERSION=${MONGO_VERSION}
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        volumes: 
            - ./mongo_databases:/var/lib/mongodb

    mongo-express:
        image: mongo-express
        ports:
            - ${MONGO_EXPRESS_PORT}:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_ADMINUSERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_ADMINPASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongo
        depends_on:
            - mongo
